### ISSUE TITLE
nao consigo abaixa

### ISSUE THREAD

**Issue by marcelowu** [dholidev/module-dholi-checkout-mirror#1]
tentei abaixar, mas precisa da senha da dependencia
"dholi/module-dholi-geoloc": "dev-master"

**Comment by dholidev** [comment]
Marcelo, bom dia.

Nossos repositórios não pedem senha no Packagist. Muito provavelmente esteja faltando o arquivo "auth.json" na raiz do seu Magento 2.

Dá uma olhada neste artigo: https://devdocs.magento.com/guides/v2.3/install-gde/prereq/dev_install.html, seção "Creating an authorization file", vai ajudar você.

Se não conseguir baixar, coloca o print do erro.

* Marcelo, este módulo ainda não tem release liberada. Por favor, não instale em ambiente de Produção.

* este pacote faz parte de uma plataforma que será lançada em breve.

Abraço.

**Comment by dholidev** [comment]
Marcelo, perdão.

O pacote "dholi/module-dholi-geoloc" foi renomeado. Já está o correto no package.json.

**Comment by marcelowu** [comment]
obrigado,
