### ISSUE TITLE
autopreenchimento de endereço nao funciona

### ISSUE THREAD

**Issue by marcelowu** [dholidev/module-dholi-checkout-mirror#2]
![Capturar1](https://user-images.githubusercontent.com/30912144/72467058-ee50bc00-37b8-11ea-81ed-f599d2702c94.PNG)
![Capturar2](https://user-images.githubusercontent.com/30912144/72467059-ee50bc00-37b8-11ea-82ea-5253f441958b.PNG)

nao esta funcionando autopreenchimento de endereço, 
magento 2.3.3 php 7.3 ubuntu 18 nginx 1.4

**Comment by dholidev** [comment]
Marcelo, dá uma olhada nessa loja: https://payu-br.dholi.dev/. Está com as mesmas configurações.

Se sua loja estiver no ar, nos consegue o endereço.

**Comment by marcelowu** [comment]
acho q o api key esta com erro.
![Capturar3](https://user-images.githubusercontent.com/30912144/72471953-653e8280-37c2-11ea-95db-80cea72a88cd.PNG)
como faço para configura certinho o api key

**Comment by marcelowu** [comment]
meu site nao esta em produção ainda

**Comment by dholidev** [comment]
Sobre a API: tem de ser do tipo "Geocoding API".

Sobre o tema: ele é gratuito "https://packagist.org/packages/dholi/module-dholi-theme-frontend".

* Marcelo, não poderei dar suporte a você no tema, ele ainda não está completo. Fica a seu critério usar.

**Comment by marcelowu** [comment]
Geocoding API eu ativei mesmo assim sem sucesso...
sera q o serviço do API eh pago?

**Comment by marcelowu** [comment]
a funcao do modulo eh somente autopreenchimento ?

**Comment by dholidev** [comment]
1 - O Geocoding é pago, entretanto, o Google te dá um limite absurdo de acessos gratuitos;

* experimente limpar a cache do navegador e o histórico. Eu prefiro usar o Firefox para desenvolver.

2 - O módulo é uma pequena peça da plataforma, além de auto-completar o endereço, ele vem com o cupom de desconto em local diferente (carrinho e checkout), com os campos ordenados e dispostos de forma diferente, com as máscaras, por ora, formatadas para o Brasil;

* no final da tarde de hoje foi atualizada a versão de demonstração "https://payu-br.dholi.dev/catalog/category/view/s/tops/id/21/" com as mesmas versões que estão públicas.

**Comment by marcelowu** [comment]
![Capturar8](https://user-images.githubusercontent.com/30912144/72557700-0a6b6080-3880-11ea-8f32-7cc99cf65629.PNG)

![Capturar7](https://user-images.githubusercontent.com/30912144/72557718-0fc8ab00-3880-11ea-8ad1-d68bbe8ddf8c.PNG)

tentei de tudo, mas ainda aparece isso.

**Comment by dholidev** [comment]
Marcelo, a mensagem está dizendo que a API do Google Maps não está ativada. É clicar no link e seguir os passos. O link que aparece para você é esse: https://developers.google.com/maps/gmp-get-started.

**Comment by marcelowu** [comment]
entendi, tem q criar uma conta aqui [https://cloud.google.com/free/docs/gcp-free-tier](url)
Valeu meu chefe

**Comment by marcelowu** [comment]
eu usei a conta normal, tem q ser conta paga(tem 1 ano gratuito)[https://cloud.google.com/free/docs/gcp-free-tier](url)
valeu meu chefe

**Comment by dholidev** [comment]
Marcelo, você pode usar a opção "Limites de uso do programa Sempre gratuito" dependendo do volume de consultas. Caso ultrapasse disso, será cobrado.
